# Generated by Django 5.0.3 on 2024-03-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
